
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OrdersDatabase.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Table_Price_DisCount
{

    public System.Guid Id { get; set; }

    public string DiscountCode { get; set; }

    public int DiscountPrecent { get; set; }

    public int UsableCount { get; set; }

    public Nullable<System.DateTime> StartDate { get; set; }

    public Nullable<System.DateTime> EndDate { get; set; }

    public string Code { get; set; }

    public string PrimaryTitle { get; set; }

    public string SecondaryTitle { get; set; }

    public string TertiaryTitle { get; set; }

    public string Url { get; set; }

    public bool IsOk { get; set; }

    public bool IsDelete { get; set; }

    public System.Guid CreatorRef { get; set; }

    public System.DateTime CreatorDate { get; set; }

    public System.Guid ModifierRef { get; set; }

    public System.DateTime ModifierDate { get; set; }

    public int Version { get; set; }

}

}
