//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_User
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public System.Guid RoleRef { get; set; }
        public Nullable<System.Guid> LanguageRef { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Identification { get; set; }
        public string RegisterCode { get; set; }
        public string Password { get; set; }
        public string EconomicCode { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public bool IsMarried { get; set; }
        public Nullable<System.DateTime> MarriedDay { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Weight { get; set; }
        public string ArchiveCode { get; set; }
        public string PersonalCode { get; set; }
        public Nullable<System.Guid> Jobs { get; set; }
        public bool IsOk { get; set; }
        public bool IsInBlacklist { get; set; }
        public bool IsSpecial { get; set; }
        public Nullable<int> Favorite { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<decimal> CommissionPercent { get; set; }
        public Nullable<System.Guid> Color { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<System.Guid> SizeRef { get; set; }
        public System.Guid CreatorRef { get; set; }
        public System.DateTime CreatorDate { get; set; }
        public System.Guid ModifierRef { get; set; }
        public System.DateTime ModifierDate { get; set; }
        public int Version { get; set; }
        public string Phone { get; set; }
        public bool IsDelete { get; set; }
    }
}
