
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OrdersDatabase.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Table_Order_Item
{

    public System.Guid Id { get; set; }

    public string Code { get; set; }

    public System.Guid OrderRef { get; set; }

    public string ItemCode { get; set; }

    public decimal Quantity { get; set; }

    public decimal Fee { get; set; }

    public Nullable<System.Guid> SizeRef { get; set; }

    public Nullable<System.Guid> ColorRef { get; set; }

    public System.Guid ItemRef { get; set; }

    public decimal Discount { get; set; }

    public decimal Addition { get; set; }

    public decimal Tax { get; set; }

    public decimal Duty { get; set; }

    public Nullable<decimal> Price { get; set; }

}

}
