//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Static_SocialMedia
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string Keys { get; set; }
        public string Value { get; set; }
        public string Entities { get; set; }
        public int Sort { get; set; }
        public bool IsOk { get; set; }
    }
}
