//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersDatabase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Order
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string ProductCode { get; set; }
        public string PostalCode { get; set; }
        public Nullable<byte> Status { get; set; }
        public string TransactionCode { get; set; }
        public string DeliveryCode { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public bool IsPay { get; set; }
        public decimal Discount { get; set; }
        public decimal Tax { get; set; }
        public decimal Duty { get; set; }
        public decimal Addition { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public bool IsOk { get; set; }
        public System.Guid ModifierRef { get; set; }
        public System.DateTime ModifierDate { get; set; }
        public System.Guid CreatorRef { get; set; }
        public System.DateTime CreatorDate { get; set; }
        public int Version { get; set; }
    }
}
