
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OrdersDatabase.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Table_Settings
{

    public System.Guid Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Family { get; set; }

    public string NationalCode { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string StartDate { get; set; }

    public string EndDate { get; set; }

    public string Token { get; set; }

    public string PrimaryTitle { get; set; }

    public string SeconderyTitle { get; set; }

    public string TertiaryTitle { get; set; }

    public string Phone { get; set; }

    public string Instagram { get; set; }

    public string Telegram { get; set; }

    public string Whatsapp { get; set; }

    public string Facebook { get; set; }

    public string Twitter { get; set; }

    public string Aparat { get; set; }

    public string Note { get; set; }

    public string Email { get; set; }

    public bool LoginType { get; set; }

    public System.Guid SiteTypeRef { get; set; }

    public bool IsOk { get; set; }

    public int Version { get; set; }

    public System.Guid CreatorRef { get; set; }

    public System.DateTime CreatorDate { get; set; }

    public System.Guid ModifierRef { get; set; }

    public System.DateTime ModifireDate { get; set; }

}

}
