//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationOrders.Models.Database.OrderDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Product_Summary
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public System.Guid ProductRef { get; set; }
        public System.Guid ColorRef { get; set; }
        public System.Guid SizeRef { get; set; }
        public System.Guid StockRef { get; set; }
        public System.Guid SaleRef { get; set; }
        public decimal Quantity { get; set; }
        public decimal Fee { get; set; }
        public int Sort { get; set; }
        public bool IsOk { get; set; }
        public bool IsDelete { get; set; }
        public bool IsMain { get; set; }
        public int Version { get; set; }
        public System.Guid CreatorRef { get; set; }
        public System.DateTime CreatorDate { get; set; }
        public System.Guid ModifierRef { get; set; }
        public System.DateTime ModifierDate { get; set; }
    }
}
